networks:
  internal:
    name: internal

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./conf:/etc/caddy
      - ./../src:/srv
    networks:
      - internal

  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: UwU
    networks:
      - internal

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - internal

  backend:
    image: cripto:backend
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./../src/backend:/app
    networks:
      - internal